# Generated by Django 5.0.7 on 2024-08-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_content_comment_cnotent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cnotent',
            new_name='content',
        ),
    ]
